# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='female', max_length=6),
        ),
    ]
