# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0002_auto_20180808_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
