# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0003_profile_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monetary_value',
            field=models.IntegerField(),
        ),
    ]
