# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0004_auto_20180809_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starting_weight',
            field=models.IntegerField(default=0),
        ),
    ]
