# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0005_profile_starting_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starting_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
