# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0009_auto_20180907_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightinput',
            name='date_added',
            field=models.DateField(),
        ),
    ]
