# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0010_auto_20180907_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightinput',
            unique_together=set([('user', 'date_added')]),
        ),
    ]
