# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weightscope_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0013_auto_20180908_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('date', models.DateField(validators=[weightscope_main.models.ensure_past])),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
