# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0017_profile_transition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='transition_date',
        ),
    ]
