# Generated by Django 3.0.5 on 2020-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0021_auto_20200421_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='key_expires',
        ),
        migrations.AddField(
            model_name='profile',
            name='password_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
