# Generated by Django 3.0.5 on 2020-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0023_auto_20200425_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
