# Generated by Django 3.0.5 on 2020-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0024_auto_20200425_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_activation_key',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.EmailField(max_length=512, unique=True),
        ),
    ]
