# Generated by Django 3.0.5 on 2020-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0025_auto_20200425_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_activation_key',
            field=models.CharField(max_length=40),
        ),
    ]
