# Generated by Django 3.0.5 on 2020-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0027_auto_20200426_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
