# Generated by Django 3.0.5 on 2020-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0029_auto_20200426_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_invites',
            field=models.IntegerField(default=5),
        ),
    ]
