# Generated by Django 3.0.5 on 2020-05-16 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0031_auto_20200509_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='initial_weight_kg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_inches',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
