# Generated by Django 3.0.5 on 2020-08-05 21:43

import datetime
from django.db import migrations, models
import weightscope_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscope_main', '0032_auto_20200516_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergy_warning_date',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0), validators=[weightscope_main.models.ensure_past]),
        ),
    ]
